version: "3"

services:
  app:
    build: .
    restart: always
    container_name: vuttr
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      - database

  database:
    image: postgres
    container_name: vuttr_database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vuttr

volumes:
  pgdata:
    driver: local
